version: '3.8'
services:
  web:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    environment:
      - API_URL=http://api:4000
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bsu_eng
      POSTGRES_USER: bsu
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
